# Generated by Django 3.1.1 on 2020-09-17 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0002_auto_20200917_1139'),
    ]

    operations = [
        migrations.AlterField(
            model_name='moviemodel',
            name='id',
            field=models.CharField(max_length=100, primary_key=True, serialize=False, unique=True),
        ),
    ]
