# Generated by Django 3.1.1 on 2020-09-17 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MovieModel',
            fields=[
                ('title', models.CharField(max_length=200)),
                ('tagline', models.CharField(max_length=500)),
                ('vote_average', models.FloatField()),
                ('vote_count', models.FloatField()),
                ('release_date', models.DateField()),
                ('poster_path', models.CharField(max_length=300, null=True)),
                ('overview', models.TextField()),
                ('budget', models.IntegerField()),
                ('revenue', models.IntegerField()),
                ('genres', models.CharField(max_length=400)),
                ('runtime', models.IntegerField(null=True)),
                ('id', models.CharField(max_length=100, primary_key=True, serialize=False, unique=True)),
            ],
            options={
                'ordering': ['-release_date'],
            },
        ),
    ]
